Homework1
made-ml-in-prod-2022/ZibyLC pull request #1
Opened 2022-05-16 20:59 UTC by ZibyLC

Mer

2022-05-20 20:52 UTC, SVizor42 commented on ml_project/src/models/predict_model.py
> +from sklearn.linear_model import LogisticRegression
Импортируется, но не используется

2022-05-20 20:53 UTC, SVizor42 commented on ml_project/src/models/predict_model.py
> +    df = pd.read_csv(data_path)
В продакшене следует давать более осмысленные имена переменным

2022-05-20 20:56 UTC, SVizor42 commented on ml_project/src/models/predict_model.py
> +def main(data_path, model_path, result_path):
Лучше не использовать безликое `main`. + нужно обратить внимание на Typing

2022-05-20 20:58 UTC, SVizor42 commented on ml_project/src/models/predict_model.py
> +    load_dotenv(find_dotenv())
Для чего здесь? Используются какие-то secrets?

2022-05-20 21:11 UTC, SVizor42 commented on ml_project/src/data/make_dataset.py
> +        train_df, test_df = train_test_split(df, test_size=0.2, stratify=df['target'], random_state=103)
Следует избегать использования MagicNumbers в проде. Если нет конфига, можно вынести в раздел констант.

2022-05-20 21:17 UTC, SVizor42 commented on ml_project/src/models/train_model.py
> +    dump(estimator, model_path)
Прежде модель желательно провалидировать и посчитать метрики

2022-05-20 21:22 UTC, SVizor42 requested changes
Отдельный плюс за использование Makefile.
Что касается замечаний, то см. комментарии. Некоторые из них носят общий характер.
Сюда же добавлю:
1. Не стоит коммитить пустые папки и файлы.
2. Есть вопросы к модульности - всего 3 основных модуля.
3. Желательно еще раз прогнать код через flake или другой линтер.

2022-05-23 09:44 UTC, ZibyLC commented on ml_project/src/models/predict_model.py
> +    load_dotenv(find_dotenv())
Здравствуйте, это было в шаблоне. По сути про запас, чтобы можно было добавить параметры окружения. Наверно стоило подчистить перед коммитом

2022-05-23 21:40 UTC, ZibyLC commented
Благодарю за обратную свзяь. Внимательно ознакомился со всеми замечаниями и пофиксил проект в последнем коммите. Отправляю в мердж

2022-05-23 21:41 UTC, merged

2022-05-27 07:35 UTC, SVizor42 commented
**Сумма: 15 * 0.6 = 9 баллов**

Хорошо. Только мерджи в следующий раз после аппрува, пжлста.